version: 2

sources:
  - name: postgres
    tables:
      - name: address
      - name: countryregion
      - name: customer
      - name: employee
      - name: person
      - name: product
      - name: salesorderheader
      - name: salesorderdetail
      - name: salesperson
      - name: salesreason
      - name: stateprovince