version: 2

sources:
  - name: production
    tables:
      - name: product
      - name: productcategory
      - name: productdescription
      - name: productsubcategory

  - name: sales
    tables:
      - name: salesorderheader
      - name: salesorderheadersalesreason
      - name: salesreason
      - name: creditcard
      - name: salesperson
      - name: customer
      - name: store
  - name: person
    tables:
        - name: person

  - name: humanresources
    tables:
        - name: employee